### ISSUE TITLE
Exception when there is no commits to push.

### ISSUE THREAD

**Issue by matrixise** [jd/git-pull-request#12]
Before to use `git pull-request` I just pushed the branch to the repository and thus, in this case, I have no commits to push, I know, the use case is not usual in your case, but maybe we could handle the case where the branch is already pushed.

```
Rebasing branch `issues-221' on branch `origin/issues-221'
Current branch issues-221 is up to date.
Force-pushing branch `issues-221' to remote `github'
Everything up-to-date
Traceback (most recent call last):
  File "/home/stephane/.local/bin/git-pull-request", line 10, in <module>
    sys.exit(main())
  File "/home/stephane/.local/lib/python2.7/site-packages/git_pull_request/__init__.py", line 341, in main
    rebase=not args.no_rebase,
  File "/home/stephane/.local/lib/python2.7/site-packages/git_pull_request/__init__.py", line 293, in git_pull_request
    body=message)
  File "/home/stephane/.local/lib/python2.7/site-packages/github/Repository.py", line 989, in create_pull
    return self.__create_pull_1(*args, **kwds)
  File "/home/stephane/.local/lib/python2.7/site-packages/github/Repository.py", line 998, in __create_pull_1
    return self.__create_pull(title=title, body=body, base=base, head=head)
  File "/home/stephane/.local/lib/python2.7/site-packages/github/Repository.py", line 1011, in __create_pull
    input=post_parameters
  File "/home/stephane/.local/lib/python2.7/site-packages/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/home/stephane/.local/lib/python2.7/site-packages/github/Requester.py", line 180, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 422 {u'documentation_url': u'https://developer.github.com/v3/pulls/#create-a-pull-request', u'message': u'Validation Failed', u'errors': [{u'message': u'No commits between issues-221 and issues-221', u'code': u'custom', u'resource': u'PullRequest'}]}
```

**Comment by jd** [comment]
Sure thing, will do!
