### ISSUE TITLE
run git pull-request fail---ImportError: cannot import name parse

### ISSUE THREAD

**Issue by xiaoyaguang** [jd/git-pull-request#18]
xiaoyaguangdeMacBook-Pro:private xiaoyaguang$ git pull-request
Traceback (most recent call last):
  File "/usr/local/bin/git-pull-request", line 7, in <module>
    from git_pull_request import main
  File "/Library/Python/2.7/site-packages/git_pull_request/__init__.py", line 24, in <module>
    from urllib import parse
ImportError: cannot import name parse

**Comment by xiaoyaguang** [comment]
Does this require specific python version or anything else I missed?

**Comment by jd** [comment]
As written in setup.cfg, it does not work with Python 2.
