### ISSUE TITLE
EOF occurred in violation of protocol (_ssl.c:777)

### ISSUE THREAD

**Issue by lee-tunnicliffe** [jd/git-pull-request#23]
Can anyone help me with this error?

```
$ git pull-request
EOF occurred in violation of protocol (_ssl.c:777)
```

**Comment by jd** [comment]
Sounds like a network problem or a SSL issue. That's bad.

**Comment by lee-tunnicliffe** [comment]
Should this work with github enterprise?

**Comment by jd** [comment]
Yes, there are some people that use it with GitHub entreprise.

**Comment by lee-tunnicliffe** [comment]
Ok, thanks, can you think of anything I can try?

**Comment by jd** [comment]
Can you try something simple like:

```python
import requests

requests.get("https://urlofyourgithubentreprise.com")
```

That should raise the same error I guess.

**Comment by lee-tunnicliffe** [comment]
```
>>> import requests
>>> requests.get("https://github.kdc.capitalone.com")
<Response [200]>
>>> 
```

**Comment by jd** [comment]
Can you run `git pull-request` with `--debug` switch to see where it fails precisely?

**Comment by lee-tunnicliffe** [comment]
```
$ git pull-request --debug
running ['git', 'rev-parse', '--abbrev-ref', 'HEAD']
Local branch name is `lees_temp_branch'
running ['git', 'config', '--get', 'branch.lees_temp_branch.merge']
running ['git', 'config', '--get', 'branch.lees_temp_branch.remote']
Target remote for branch `lees_temp_branch' is `origin'
running ['git', 'config', '--get', 'remote.origin.url']
Remote URL for remote `origin' is `<urlofmygithubentreprise.com>'
GitHub user and repository to fork: <myrepo> on <urlofmygithubentreprise.com>
Found GitHub user: `lee.tunnicliffe@urlofmygithubentreprise.com' password: <redacted>
Using API base url `https://urlofmygithubentreprise.com/api/v3'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/git-pull-request", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/git_pull_request/__init__.py", line 486, in main
    download=args.download,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/git_pull_request/__init__.py", line 229, in git_pull_request
    repo = g.get_user(user_to_fork).get_repo(reponame_to_fork)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/github/MainClass.py", line 168, in get_user
    "/users/" + login
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/github/Requester.py", line 213, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/github/Requester.py", line 252, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/github/Requester.py", line 277, in __requestRaw
    requestHeaders
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:777)
```

**Comment by jd** [comment]
This seems to be a problem with OS X and linking to an old SSL lib or something. They are plenty of report on the Web about that such as https://github.com/requests/requests/issues/3006
